### ISSUE TITLE
Recommendation: Promote styling `outline-width` over `outline`

### ISSUE THREAD

**Issue by jonathantneal** [WICG/focus-ring#38]
To preserve user agent outline styles, I recommend you promote styling `outline-width` instead of `outline`:

```css
:focus:not(.focus-ring) {
    outline-width: none;
}
```

This allows overrides to restore user agent styles:

```css
.override:focus {
    outline-width: medium;
}
```
