### ISSUE TITLE
Brainstorm: options for opting in to always matching focus ring

### ISSUE THREAD

**Issue by alice** [WICG/focus-ring#42]
We know we need a way to opt an element in to always (or never?) getting a focus ring. Let's talk about strategies for doing this.

**Comment by alice** [comment]
**Proposal: just use `:focus`**

Use the existing `:focus` pseudo-selector to opt an element in to always getting a focus ring on focus. Requires a way to recover the platform default focus style, assuming `:focus-ring` will be the UA default in future.

**Example**

```css
:focus {
  outline: platform-default;  /* need a way to express this */ 
}
```

**Comment by alice** [comment]
**Proposal: add a new CSS property to express when an element should match `:focus-ring`**

Allow an element to opt in to `:focus-ring` matching the way built-in text editing elements do. Potentially also allows fine tuning focus-ring matching at page author discretion.

**Example**
/* all syntax to be considered a "straw man" */

```css
custom-text-editor {
  show-focusring: always;
}

div[tabindex=-1] {
  show-focusring: never;  /* may potentially be overridden by user preference */
}

* {
  /* match when focus is moved via the keyboard explicitly, i.e. tab/shift-tab */
  show-focusring: explicit-focus; 
}

button {
  show-focusring: on-keypress;
}
```
